pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ./adf/*
    exclude:
      - azure-pipelines*.yml

variables:
  - name: adfDevSubscription
    value: '7806cf8d-3992-4f6a-ab99-e493a143ad1b'
  - name: adfDevResourceGroup
    value: 'poc-cicd-azure-datalake'
  - name: adfDevFactoryName
    value: 'datalake-dev-1418475243'

stages:
  - stage: build_arm_templates
    displayName: 'Build ARM Templates'
    jobs:
      - job: generate_arm
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'
          displayName: 'Install Node.js'
        - script: |
            npm --prefix '$(System.DefaultWorkingDirectory)/adf' install
          displayName: 'Install npm package'
        - script: |
            npm --prefix '$(System.DefaultWorkingDirectory)/adf' run build validate $(System.DefaultWorkingDirectory)/adf /subscriptions/$(adfDevSubscription)/resourceGroups/$(adfDevResourceGroup)/providers/Microsoft.DataFactory/factories/$(adfDevFactoryName)
          displayName: 'Validate'
        - script: |
            npm --prefix '$(System.DefaultWorkingDirectory)/adf' run build export $(System.DefaultWorkingDirectory)/adf /subscriptions/$(adfDevSubscription)/resourceGroups/$(adfDevResourceGroup)/providers/Microsoft.DataFactory/factories/$(adfDevFactoryName) 'ArmTemplate'
          displayName: 'Validate and Generate ARM template'
        - publish: '$(System.DefaultWorkingDirectory)/adf/ArmTemplate'
          artifact: 'ArmTemplates'
  - stage: deploy_adf_qa
    dependsOn: build_arm_templates
    displayName: 'Deploy ADF QA'
    variables:
      - group: 'contoso-adf-qa'
    jobs:
      - deployment: deploy_adf_qa
        environment: contoso-adf-qa
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: 'ArmTemplates'
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'Azure Internal (7806cf8d-3992-4f6a-ab99-e493a143ad1b)'
                    subscriptionId: '7806cf8d-3992-4f6a-ab99-e493a143ad1b'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: 'poc-cicd-azure-datalake'
                    location: 'West US 2'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
                    csmParametersFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateParametersForFactory.json'
                    overrideParameters: $(overrideParameters)
                    deploymentMode: 'Incremental'
  - stage: deploy_adf_prod
    dependsOn: deploy_adf_qa
    displayName: 'Deploy ADF Prod'
    variables:
      - group: 'contoso-adf-prod'
    jobs:
      - deployment: deploy_adf_prod
        environment: contoso-adf-prod
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: 'ArmTemplates'
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'Azure Internal (7806cf8d-3992-4f6a-ab99-e493a143ad1b)'
                    subscriptionId: '7806cf8d-3992-4f6a-ab99-e493a143ad1b'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: 'poc-cicd-azure-datalake'
                    location: 'West US 2'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
                    csmParametersFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateParametersForFactory.json'
                    overrideParameters: $(overrideParameters)
                    deploymentMode: 'Incremental'
              